name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
